src/plugins/custom_import_map/public/components/vector_upload_options.test.tsx, src/plugins/custom_import_map/public/index.ts, src/plugins/custom_import_map/public/plugin.tsx, src/plugins/custom_import_map/public/services.ts, src/plugins/custom_import_map/public/types.ts, src/plugins/custom_import_map/server/index.ts, src/plugins/custom_import_map/server/plugin.ts, src/plugins/custom_import_map/server/types.ts
An intermittent failure is seen in running the tests via github actions - `FATAL ERROR: MarkCompactCollector: young object promotion failed Allocation failed - JavaScript heap out of memory` eg. https://github.com/opensearch-project/dashboards-maps/runs/6872023951?check_suite_focus=true. This PR helps in resolving the issue and also updates license headers in few files that were missing from the initial commit.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origi …
=> Fixes failing tests and updates license headers in files

src/plugins/custom_import_map/common/constants/shared.ts, src/plugins/custom_import_map/common/index.ts, src/plugins/custom_import_map/public/components/__snapshots__/vector_upload_options.test.tsx.snap, src/plugins/custom_import_map/public/components/vector_upload_options.test.tsx, src/plugins/custom_import_map/public/components/vector_upload_options.tsx
- Fixes issue that can be seen in case we drag any non geojson/json file into file import box.
If we drag any non json file, following toast is displayed:
- Improves danger toast messaging in case random json file is imported.
In case we upload non-geojson format files, following toasts are displayed to the user:
- File validation to kick in when random files are being dragged into the file import box.
- Make error message more intuitive in case random json file is imported. …
=> Fixes issue with file validation and danger toast messages

.github/workflows/unit-tests-workflow-for-customImportMap.yml, DEVELOPER_GUIDE.md, src/plugins/custom_import_map/package.json, src/plugins/custom_import_map/public/components/vector_upload_options.test.tsx, src/plugins/custom_import_map/public/components/vector_upload_options.tsx, src/plugins/custom_import_map/public/plugin.tsx, src/plugins/custom_import_map/public/services.ts, src/plugins/custom_import_map/public/types.ts, src/plugins/custom_import_map/server/index.ts, src/plugins/custom_import_map/server/plugin.ts, src/plugins/custom_import_map/test/jest.config.js
- Modifies path references so that `src/plugins` can be removed while adding `custom_import_map` plugin to OSD
- Successfully ran the following commands: 
- `yarn start` and tested out that the functionality works as expected
- `yarn run test:jest --coverage --coverageDirectory=. -u` 
- `yarn plugin-helpers build --opensearch-dashboards-version=2.2.0.0`
```
yarn run v1.22.18
warning package.json: No license field
$ node ../../scripts/plugin_helpers build --opensearch-dashboards-version=2.2.0.0
info deleting the build and target directories
info running @osd/optimizer
│ info initialized, 0 bundles cached
│ info starting worker [1 bundle]
│ succ 1 bundles compiled successfully after 21 sec
info copying assets from `public/assets` to build …
```
=> adds changes for releasing plugin with OSD as part of 2.2 release

release-notes/opensearch-dashboards-maps.release-notes-2.2.0.0.md
Update release notes to include each PR
https://github.com/opensearch-project/dashboards-maps/issues/17
=> Update 2.2.0.0 release note

src/plugins/custom_import_map/opensearch_dashboards.json, src/plugins/custom_import_map/package.json, src/plugins/custom_import_map/test/jest.config.js
- To remain consistent with the other dashboards plugins, added suffix to plugin name
- Also, added missing properties in package.json
Tested building the plugin zip -
```
yarn build
yarn run v1.22.18
$ yarn plugin-helpers build
$ node ../../scripts/plugin_helpers build
info deleting the build and target directories
info running @osd/optimizer
│ info initialized, 0 bundles cached
│ info starting worker [1 bundle]
│ succ 1 bundles compiled successfully after 34.7 sec
info copying assets from `public/assets` to build
info copying server source into the build and converting with babel
info running yarn to install dependencies
info compressing plugin into [customImportMapDashboards-2.2.0.zip]
✨  Done in 44.34s.
```
By submitting this pull …
=> Adds dashboards as suffix to plugin name

.github/workflows/cypress-workflow.yml
- Changes geospatial plugin branch to 2.3 to fix failure seen on running cypress tests.
Workflow failure can be found here: https://github.com/opensearch-project/dashboards-maps/runs/8257005866?check_suite_focus=true
=> adds fix for running cypress tests in 2.3 branch

src/plugins/maps_dashboards/public/components/add_layer_panel/add_layer_panel.scss, src/plugins/maps_dashboards/public/components/add_layer_panel/add_layer_panel.tsx, src/plugins/maps_dashboards/public/components/add_layer_panel/index.ts, src/plugins/maps_dashboards/public/components/layer_control_panel/layer_control_panel.scss, src/plugins/maps_dashboards/public/components/layer_control_panel/layer_control_panel.tsx, src/plugins/maps_dashboards/public/index.scss
Added UI: add layer button, hide layer button and delete layer button.
Added function: When click on "Add layer" button at layer control panel, it will go to **Add layer panel** modal.
=> Add layer panel component

src/plugins/maps_dashboards/common/index.ts
Since OpenSearch maps service vector tiles service are ready to use with basic style, updating maps vector tile service url in this PR.
Closes https://github.com/opensearch-project/dashboards-maps/issues/57
=> Update maps vector tile service url

maps_dashboards/common/index.ts, maps_dashboards/package.json, maps_dashboards/public/components/add_layer_panel/add_layer_panel.tsx, maps_dashboards/public/components/layer_config/layer_config_panel.tsx, maps_dashboards/public/components/layer_control_panel/layer_control_panel.tsx, maps_dashboards/public/components/map_container/map_container.scss, maps_dashboards/public/components/map_container/map_container.tsx, maps_dashboards/public/model/ILayerConfig.ts, maps_dashboards/public/model/OSMLayerFunctions.ts, maps_dashboards/public/model/layersFunctions.ts, maps_dashboards/yarn.lock
* Allow to add and delete layers of OpenSearch maps layer.
* Move all layers function logic to Model folder.
* Add current zoom level display at right bottom on maps page.
https://github.com/opensearch-project/dashboards-maps/issues/61
https://user-images.githubusercontent.com/90288540/197291680-baec2c4c-7c8a-48b3-8a95-4192c853610f.mov
=> add new layer functions for opensearch map layer

.github/workflows/unit-tests-workflow-for-customImportMap.yml, src/plugins/custom_import_map/package.json, src/plugins/custom_import_map/test/jest.config.js
Add window and mac platform to run unit test
Similar to what has been done in main branch. https://github.com/opensearch-project/dashboards-maps/pull/63
https://github.com/opensearch-project/dashboards-maps/issues/55
=> Add window and mac platform to run unit test

.github/workflows/unit-tests-workflow-for-customImportMap.yml, src/plugins/custom_import_map/package.json, src/plugins/custom_import_map/test/jest.config.js
Add window and mac platform to run unit test
=> [Backport 2.4] Add window and mac platform to run unit test (#74)

maps_dashboards/common/index.ts, maps_dashboards/public/components/app.tsx, maps_dashboards/public/components/layer_control_panel/layer_control_panel.tsx, maps_dashboards/public/components/map_container/map_container.tsx, maps_dashboards/public/components/map_page/map_page.tsx, maps_dashboards/public/components/map_top_nav/get_top_nav_config.tsx, maps_dashboards/public/components/map_top_nav/top_nav_menu.tsx, maps_dashboards/public/components/maps_list/maps_list.tsx, maps_dashboards/public/model/OSMLayerFunctions.ts, maps_dashboards/public/model/layersFunctions.ts, maps_dashboards/public/plugin.ts, maps_dashboards/public/types.ts, maps_dashboards/public/utils/breadcrumbs.ts, maps_dashboards/tsconfig.json
* Integrate map layers to store
* Add saved map to route in the format of `app/maps-dashboards/{id}` 
* Add breadcrumbs to listing page, create and saved map page
https://github.com/opensearch-project/dashboards-maps/issues/68
https://user-images.githubusercontent.com/90288540/199593239-3b72cdc1-5b47-4093-8657-25aaa2567377.mov
=> Integrate layerList to store and add breadcrumbs

maps_dashboards/public/components/layer_config/layer_basic_settings.tsx, maps_dashboards/public/model/layersFunctions.ts, maps_dashboards/public/model/mapLayerType.ts
Include following fields to basic layer settings
- Type : to show layer type, ex: Documents, OpenSearch Map, Custom Map, etc ...
- Description: to accept more than one to describe layer description
- Rename to Zoom levels
=> Update basic layer settings

maps_dashboards/public/components/layer_config/document_layer_source.tsx
Document layer will have more than one section like filtering and tool tip.
This will occupy lot of space vertically. 
Having collapsible will help user to get to section faster.
By default, Documents section will be expanded and rest of the  sections will be collapsed.
=> Add collapsible section to Documents

maps_dashboards/public/components/add_layer_panel/add_layer_panel.tsx, maps_dashboards/public/components/layer_control_panel/layer_control_panel.scss, maps_dashboards/public/components/layer_control_panel/layer_control_panel.tsx
Update layer control panel:
- Greyed out selected layer name when layer config panel is open.
- Fix click twice layer name to open layer config panel issue.
- Disable add new layer button when layer config panel is open.
=> Update layer control panel

maps_dashboards/common/index.ts, maps_dashboards/public/components/layer_control_panel/layer_control_panel.tsx
Based on hide/show layer available,  eye closed or eye icon will be displayed.
=> Update show/hide icon

maps_dashboards/public/components/layer_control_panel/layer_control_panel.scss, maps_dashboards/public/components/layer_control_panel/layer_control_panel.tsx
Added icon to trigger re-order layer inside panel. Increased panel width to accommodate new icon.
=> Add reorder handle inside layer panel

maps_dashboards/common/index.ts, maps_dashboards/public/components/layer_config/layer_basic_settings.tsx
1. Name cannot be empty.
2. Name cannot be more than 35 characers length.
This will only trigger UI error. The user will still be able to save with error. Disable save if error exists will be added in later PR.
=> Add validation for layer basic settings

custom_import_map/build.sh
Migrate custom-import-map build script to plugin component path from OpenSearch-build [scripts/components/customImportMapDashboards/build.sh](https://github.com/opensearch-project/opensearch-build/blob/main/scripts/components/customImportMapDashboards/build.sh). The build script have less two ../ since moved plugin since we changed the plugin to repo root path.
Need to hold this PR to be merged after 2.4.1 release out
https://github.com/opensearch-project/dashboards-maps/issues/83 …
=> Migrate custom-import-map build script to plugin component path

maps_dashboards/public/components/add_layer_panel/add_layer_panel.tsx, maps_dashboards/public/components/layer_config/base_map_layer_config_panel.tsx, maps_dashboards/public/components/layer_config/documents_config/document_layer_config_panel.tsx, maps_dashboards/public/components/layer_config/documents_config/document_layer_source.tsx, maps_dashboards/public/components/layer_config/layer_basic_settings.tsx, maps_dashboards/public/components/layer_config/layer_config_panel.tsx, maps_dashboards/public/components/layer_control_panel/layer_control_panel.tsx, maps_dashboards/public/components/map_page/map_page.tsx, maps_dashboards/public/components/map_top_nav/get_top_nav_config.tsx, maps_dashboards/public/components/map_top_nav/top_nav_menu.tsx, maps_dashboards/public/model/documentLayerFunctions.ts, maps_dashboards/public/utils/getIntialLayerConfig.ts, maps_dashboards/tsconfig.json
Signed-off-by: Junqiu Lei [junqiu@amazon.com](mailto:junqiu@amazon.com)
This PR contains:
- Add new layer type name to layer panel list when click add new type of layer
- Fix navigation name to be saved map name once after click save map
- Disable update button when have incomplete configuration or invalid input
- Add warning modal when user wants leave unsaved configuration panel
- Separate initial layer configuration to until folder
https://user-images.githubusercontent.com/90288540/207206034-45767b8f-974f-4dc7-bf3b-838f9f5a8c49.mov …
=> Enhance user workflow logic

maps_dashboards/public/components/layer_control_panel/layer_control_panel.tsx, maps_dashboards/public/model/documentLayerFunctions.ts
Include tooltip fields to source
- Fetch tooltip fields from cluster, if show tooltip
is enabled and tooltips are added.
- Move tooltip fields to properties
=> Fetch tooltip fields from cluster

maps_dashboards/public/components/layer_control_panel/layer_control_panel.tsx
Reverse layers order on layer control panel, so that the layers order on panel can be consistent with layers order in map. 
=> Reverse layer list on layer panel

maps_dashboards/public/components/layer_config/documents_config/document_layer_source.tsx, maps_dashboards/public/components/layer_control_panel/layer_control_panel.tsx, maps_dashboards/public/model/mapLayerType.ts
Adding filters to map layer which allows user to do more accurate and customized searches
=> feat: display search filters in map layer config panel

maps_dashboards/public/_variables.scss, maps_dashboards/public/components/add_layer_panel/add_layer_panel.tsx, maps_dashboards/public/components/layer_config/documents_config/document_layer_config_panel.tsx, maps_dashboards/public/components/layer_config/documents_config/document_layer_source.tsx, maps_dashboards/public/components/layer_config/layer_config_panel.tsx, maps_dashboards/public/components/layer_control_panel/layer_control_panel.tsx, maps_dashboards/public/components/map_container/map_container.scss, maps_dashboards/public/components/map_container/map_container.tsx, maps_dashboards/public/components/map_page/map_page.tsx, maps_dashboards/public/components/map_top_nav/get_top_nav_config.tsx, maps_dashboards/public/components/map_top_nav/top_nav_menu.tsx, maps_dashboards/public/model/DataLayerController.ts, maps_dashboards/public/model/mapLayerType.ts, maps_dashboards/public/model/mapState.ts, maps_dashboards/public/utils/getIntialConfig.ts
This PR is for global filter bar which can be used to filter timeline for all indexPatterns.
https://user-images.githubusercontent.com/90288540/209018202-232bf1e7-d7b9-4801-9afc-7b520c298fc7.mov
https://github.com/opensearch-project/dashboards-maps/issues/103
=> Add global filter bar to maps

maps_dashboards/public/components/map_container/map_container.tsx, maps_dashboards/public/components/tooltip/create_tooltip.tsx, maps_dashboards/public/components/tooltip/tooltipContainer.tsx, maps_dashboards/public/components/tooltip/tooltipHeaderContent.tsx, maps_dashboards/public/components/tooltip/tooltipTable.tsx, maps_dashboards/public/model/DataLayerController.ts, maps_dashboards/public/model/documentLayerFunctions.ts
Refactor map popup rendering logic, 
1. Abstract a reusable popup rendering logic.
2. For click-popups which need to display multi-layers information, added an event listener globally and then query features from all layers at the current position.
3. For hover-popups which show information of the current layer features, moved the popup rendering logic out from the layer render logic(in the layer control panel component).
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate …
=> feat: added multi-layer support to map popup

maps_dashboards/public/components/layer_control_panel/layer_control_panel.tsx, maps_dashboards/public/model/layersFunctions.ts
if layer is moved below, the drag drop destination provides where layer should be added before.
if layer is moved above, the drag drop destination provides where layer should be added above. Hence, move to next layer to find before layer index.
Demo:
https://user-images.githubusercontent.com/11067894/209039792-f878053a-0905-4d19-a369-c260d141e4ff.mov
=> Move layer if layer order is changed

maps_dashboards/public/model/documentLayerFunctions.ts, maps_dashboards/public/utils/geo_formater.ts
Support Geopoint as 
1. GeoJSON
2. String
3. Array of lon and lat
WKT and Geohash will be supported in later release.
=> Support other geopoint formats

maps_dashboards/common/index.ts, maps_dashboards/public/components/add_layer_panel/add_layer_panel.tsx, maps_dashboards/public/components/layer_config/documents_config/document_layer_source.tsx, maps_dashboards/public/components/layer_config/layer_config_panel.tsx, maps_dashboards/public/components/layer_control_panel/layer_control_panel.tsx, maps_dashboards/public/components/map_page/map_page.tsx, maps_dashboards/public/components/tooltip/tooltipTable.tsx, maps_dashboards/public/model/layerRenderController.ts, maps_dashboards/public/model/layersFunctions.ts, maps_dashboards/public/utils/getIntialConfig.ts
1. Set new layer name as New layer <number>
2. Set default OpenSearch Map as "Default map"
3. Added tooltip for buttons
4. Layer type icon is added before title
Demo
Icons are updated as below and updated layer names
Add layer panel
Layer type Icon is added before tile
=> Improve UX

maps_dashboards/public/components/layer_control_panel/layer_control_panel.tsx
Disable selected layer delete button when config panel open.
=> Disable selected layer delete button when config panel open

maps_dashboards/public/components/layer_config/documents_config/document_layer_source.tsx, maps_dashboards/public/components/tooltip/tooltipTable.tsx
- Update layer selection combo box
- Use check box instead of switch
=> Update UI based on review

maps_dashboards/public/components/layer_config/documents_config/document_layer_config_panel.tsx, maps_dashboards/public/components/layer_config/documents_config/document_layer_source.tsx, maps_dashboards/public/components/layer_config/documents_config/document_layer_style.tsx, maps_dashboards/public/components/layer_config/layer_config_panel.tsx, maps_dashboards/public/components/layer_control_panel/layer_control_panel.tsx
This PR contains:
- Fixes documents layer data source property not update properly when directly  switch to another layer
- Adds warn modal for unsaved layer configuration when want switch to another layer.
###Demo
https://user-images.githubusercontent.com/90288540/210870457-94cbc36d-0367-4524-9b21-eb644e8e5121.mov
=> Update property when switching layer config panel

maps_dashboards/public/components/layer_control_panel/layer_control_panel.scss, maps_dashboards/public/components/layer_control_panel/layer_control_panel.tsx, maps_dashboards/public/components/map_container/map_container.tsx
Display current visible layer information on the layer control panel. 
- When the layer zoom range in current zoom level, its layer icon will be colorful, else it will be text color.
- When the layer zoom range is out of current zoom level, move mouse to layer name, the tooltip will show it's out of zoom range.
https://user-images.githubusercontent.com/90288540/211118787-b7532b72-ebd9-4cb5-a9f1-079fa69631a7.mov …
=> Display current visible layers status

maps_dashboards/public/components/layer_config/documents_config/document_layer_source.tsx, maps_dashboards/public/components/map_container/map_container.tsx, maps_dashboards/public/components/tooltip/create_tooltip.tsx, maps_dashboards/public/model/documentLayerFunctions.ts, maps_dashboards/public/model/layerRenderController.ts, maps_dashboards/public/model/mapLayerType.ts
1. When the map application is opened(initial load), it will query data with the current map bounds
2. When user zoom in/out, move the map, resize the window, etc. New queries will be fired with the updated bounding box and then update the map accordingly.
- fixed wrong maplibre instance passed to addTooltip() function which results in a runtime error
- fixed empty onHover popup rendered on layer which has tooltip disabled
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificat …
=> feat: query with geo bounding box

package.json, public/components/layer_config/documents_config/document_layer_config_panel.tsx, public/components/layer_config/documents_config/document_layer_source.tsx, public/components/layer_config/documents_config/document_layer_style.tsx, public/components/layer_config/layer_config_panel.tsx, public/components/layer_control_panel/layer_control_panel.scss, public/components/layer_control_panel/layer_control_panel.tsx, public/components/map_container/map_container.tsx, public/components/tooltip/create_tooltip.tsx, public/model/documentLayerFunctions.ts, public/model/layerRenderController.ts, public/model/mapLayerType.ts, public/utils/geo_formater.ts, tsconfig.json, yarn.lock
Merge Feature/new maps branch head to main after https://github.com/opensearch-project/dashboards-maps/pull/166 merged.
This PR contains:
https://github.com/opensearch-project/dashboards-maps/pull/158
https://github.com/opensearch-project/dashboards-maps/pull/165
https://github.com/opensearch-project/dashboards-maps/pull/154
https://github.com/opensearch-project/dashboards-maps/pull/159
https://github.com/opensearch-project/dashboards-maps/pull/148
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTIN …
=> Merge Feature/new-maps branch head to main

public/model/customLayerFunctions.ts, public/model/documentLayerFunctions.ts
Fix the issue when open saved map, zoom range can't load for documents layer and custom layer.
=> Update zoom range render logic

.github/workflows/cypress-workflow.yml, .github/workflows/unit-tests-workflow.yml, cypress/integration/documentsLayer.spec.js, cypress/integration/geojson_file_upload.spec.js, cypress/integration/import_vector_map_tab.spec.js, cypress/integration/opensearchMapLayer.spec.js, cypress/plugins/index.js, cypress/support/index.js, package.json, public/components/add_layer_panel/add_layer_panel.tsx, public/components/layer_config/documents_config/document_layer_config_panel.tsx, public/components/layer_config/documents_config/document_layer_source.tsx, public/components/layer_config/layer_config_panel.tsx, public/components/layer_control_panel/layer_control_panel.tsx, public/components/map_container/map_container.tsx, public/components/maps_list/maps_list.tsx, yarn.lock
Unblock existing CI workflows for both cypress test and unit test and add cypress test cases for new maps.
=> Update existing CI workflow

common/index.ts, public/model/layerRenderController.ts
if more than one copies are visible, use max bounds else wrap bounds to cover international date line.
=> Update mapbounds logic

common/index.ts, public/model/layerRenderController.ts
Backport https://github.com/opensearch-project/dashboards-maps/commit/7eb646e381337fcc9151d0c881b5b0dbe9ca4f14 from https://github.com/opensearch-project/dashboards-maps/pull/175
=> [Backport 2.5]  Update mapbounds logic (#175)

public/components/layer_config/layer_basic_settings.tsx, public/components/layer_config/layer_config_panel.tsx
Move layer type UI on config panel from panel body Input to header, we got input from UX that the existing uneditable Input to display layer type may be confused on UI.
Before:
After:
=> Update layer type UI on config panel

public/plugin.tsx
Move maps entrypoint under plugins. Finally It will be at above notifications, below anomaly detection plugin.
=> Move maps entrypoint under plugins

common/index.ts, public/application.tsx, public/components/add_layer_panel/add_layer_panel.tsx, public/components/app.tsx, public/components/layer_control_panel/layer_control_panel.tsx, public/components/map_container/map_container.tsx, public/components/map_page/map_page.tsx, public/config.ts, public/index.ts, public/plugin.tsx, public/utils/getIntialConfig.ts, release-notes/opensearch-dashboards-maps.release-notes-2.5.0.0.md, server/index.ts
Allow user to override maps service url configuration from OpenSearch-Dashboard config yml file by adding:
```
custom_import_map_dashboards.opensearchVectorTileDataUrl: "https://tiles.maps.opensearch.org/data/v1.json"
custom_import_map_dashboards.opensearchVectorTileStyleUrl: "https://tiles.maps.opensearch.org/styles/basic.json"
custom_import_map_dashboards.opensearchVectorTileGlyphsUrl: "https://tiles.maps.opensearch.org/fonts/{fontstack}/{range}.pbf"
```
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CON …
=> Support overriding maps config from OSD config yml file

common/index.ts, public/components/add_layer_panel/add_layer_panel.tsx, public/components/layer_control_panel/layer_control_panel.tsx
Add restriction to create more than 100 layers.
I took snapshot with 3 as max limit to avoid creating 20 layers
=> Limit max number of layers

.github/workflows/cypress-workflow.yml, cypress/integration/documentsLayer.spec.js
Wait map saved before redirect to maps listing page, so that void not able to find saved map in listing page. This issue only happens in GH action cypress CI window OS.
https://github.com/opensearch-project/dashboards-maps/issues/210
=> [Cypress fix] Wait map saved before open maps listing

public/components/layer_control_panel/layer_control_panel.tsx, public/model/OSMLayerFunctions.ts, public/model/customLayerFunctions.ts, public/model/documentLayerFunctions.ts, public/model/layersFunctions.ts, public/model/map/__mocks__/map.ts, public/model/map/layer_operations.test.ts, public/model/map/layer_operations.ts
Refactor following layer operations
1. getLayer
2. hasLayer
3. removeLayer
4. moveLayer
5. updateVisibility
=> Refactor layer operations

public/model/customLayerFunctions.ts, public/model/map/layer_operations.ts
Remove unused methods
Refactor common properties
=> Refactor layer properties as own interface

public/components/layer_control_panel/layer_control_panel.tsx, public/components/map_container/map_container.tsx, public/components/tooltip/create_tooltip.tsx
While zoom out, maps will have multiple copies of world map. Before this fix, popup will be displayed always at first copy even if users are hovering over another copy. This will make sure that hover shows up on where pointer is hovered.
=> Fix popup display while zoomed out

.github/workflows/cypress-workflow.yml
Add more wait time for OSD start run to fix flaky test on cypress ci
https://github.com/opensearch-project/dashboards-maps/actions/runs/4120910890/jobs/7116107984
=> Fix flaky test on cypress ci

package.json, public/components/layer_control_panel/delete_layer_modal.test.tsx, public/components/layer_control_panel/delete_layer_modal.tsx, public/components/layer_control_panel/layer_control_panel.tsx
Move delete layer modal into different component and added test.
=> Refactor delete layer modal

cypress/integration/add_saved_object.spec.js, opensearch_dashboards.json, server/plugin.ts, server/services/sample_data/flights_saved_objects.ts, server/types.ts
This PR includes the changes which adds the dashboards-maps saved object to the existing sample dataset. When the user install a sample dataset then in the dashboards-maps panel, we can see a default saved map which will help maps users to explore maps with that dataset instead of creating a new map from scratch.
We have two videos below which shows the dashboards-maps panel before adding these changes and after adding these changes for flights sample dataset. Similarly, we can add saved objects for other sample datasets. 
https://user-images.githubusercontent.com/89161683/218019859-c7a7f575-ddb1-4afa-807a-a07c43507dd1.mov
https://user-images.githubusercontent.com/89161683/218020002-38131051-953f-49fa-ac1f-695e0ccd92e5.mov
Tested it to make sure the saved object consumes the latest …
=> Add maps saved object for sample datasets

public/components/map_container/map_container.tsx, public/components/tooltip/create_tooltip.tsx
When large number of points and shapes are rendered on same location, tooltip occasionally is not cleared. 
Adding close button will solve this problem temporarily to unblock users have to reload map to get rid of dangling tooltip contents.
#259 
=> Add close button to tooltip hover

common/constants/shared.ts, common/index.ts, cypress/integration/add_map_to_dashboard.spec.js, opensearch_dashboards.json, package-lock.json, public/components/add_layer_panel/add_layer_panel.tsx, public/components/app.tsx, public/components/layer_control_panel/layer_control_panel.tsx, public/components/map_container/map_container.scss, public/components/map_container/map_container.tsx, public/components/map_page/map_page.tsx, public/components/map_top_nav/get_top_nav_config.tsx, public/components/map_top_nav/top_nav_menu.tsx, public/components/maps_list/maps_list.tsx, public/embeddable/index.ts, public/embeddable/map_component.tsx, public/embeddable/map_embeddable.tsx, public/embeddable/map_embeddable_factory.tsx, public/model/layerRenderController.ts, public/plugin.tsx, public/services.ts, public/types.ts, public/utils/breadcrumbs.ts, yarn.lock
Allow user to add maps to dashboard.  This PR contains:
* Maps embeddable api
* Refactor maps component to adapt embeddable
* Saved map can be added and displayed to dashboards
* Register maps into visualization entrypoint
* Editing map can be saved and return to dashboard
* Time range in dashboard can be effected to map
* Filter in dashboard can be effected to map
* Interval refresh in dashboard can be effected to map
* Cypress test
https://user-images.githubusercontent.com/90288540/217351975-9bc84331-617f-4ef0-b4e0-d2d7af65254e.mov
https://user-images.githubusercontent.com/90288540/218572172-9af1e6fd-1bb3-4db7-ba45-c0b7ae8fa60a.mov
https://github.com/opensearch-project/dashboards-maps/issues/214
By submitting this pull request, I confirm …
=> Add map as embeddable to dashboard

public/components/add_layer_panel/add_layer_panel.scss, public/components/add_layer_panel/add_layer_panel.tsx
Align different type layer items in the add new layer modal.
Before:
After:
=> Align items in add new layer modal

public/components/layer_control_panel/layer_control_panel.scss, yarn.lock
Add scroll bar when more layers added on panel, set a max height to the layer list panel. In screen displayed layers will be maximum to 6.
=> Add scroll bar when more layers added

public/components/layer_config/documents_config/document_layer_config_panel.tsx, public/components/layer_config/layer_config_panel.tsx, public/components/layer_control_panel/layer_control_panel.tsx, public/components/map_container/map_container.tsx, public/components/map_page/map_page.tsx, public/components/map_top_nav/top_nav_menu.tsx, public/embeddable/map_component.tsx, public/model/layerRenderController.ts, public/model/layersFunctions.ts
Move layer handlers from layerControlPanel component to it's parent mapContainer component. The refactoring also fixed the duplicate handler call when in viewOnlyMode(dashboard mode).
https://github.com/opensearch-project/dashboards-maps/issues/270
=> Refactor layer handler into parent component

public/embeddable/map_embeddable.tsx, public/embeddable/map_embeddable_factory.tsx
In dashboard global filter bar component, it need read indexPatterns information from maps embeddable output to correctly show the maps data layers indexPattern.
Consuming ref: https://github.com/opensearch-project/OpenSearch-Dashboards/blob/main/src/plugins/dashboard/public/application/dashboard_app_controller.tsx#L292
https://github.com/opensearch-project/dashboards-maps/issues/214
=> Add indexPatterns to map embeddable output for dashboard filters

.github/workflows/cypress-workflow.yml, .github/workflows/unit-tests-workflow.yml
The GitHub workflow uses the `engines` from OSD incorrectly. This change fixes that.
=> Fix Node.js and Yarn installation in CI

public/model/documentLayerFunctions.ts
If property value is false, property is not added. Replace check with undefined to accept false value.
=> Fix property value's non null check

public/model/customLayerFunctions.ts, release-notes/opensearch-dashboards-maps.release-notes-2.6.0.0.md
Fix custom layer render opacity config missed when re-open saved map.
https://github.com/opensearch-project/dashboards-maps/issues/290
=> Fix custom layer render opacity config

.gitignore, public/components/layer_control_panel/layer_control_panel.scss
Show scroll bar when layer control panel height reaches map container bottom.
https://user-images.githubusercontent.com/90288540/221646365-a98ed3fc-4592-4380-b3d1-4902425f594a.mov
Closes #293
=> Show scroll bar when panel height reaches container bottom

public/components/layer_control_panel/layer_control_panel.tsx
Enhance layer visibility status display.
Priority 0: When layer visibility is none: 1) show tooltip "layer is hidden" and 2) gray out the icon and layer name
Priority 1: When layer setting zoom level range is out of current zoom level, 1) show tooltip "layer is not visible outside of zoom range a to b" and 2) gray out the icon and layer name
Closes https://github.com/opensearch-project/dashboards-maps/issues/298
=> Enhance layer visibility status display

public/model/customLayerFunctions.ts
This PR to fix the custom layer visibility config to render, meanwhile combine all the configurations together to call by `addLayer` instead of call all the APIs separately.
Closes https://github.com/opensearch-project/dashboards-maps/issues/296
=> Add custom layer visibility config to render

public/components/layer_config/documents_config/document_layer_source.tsx
+ fixed the issue of filters selection not being restored/cleared when switching among index patterns
+ fixed the issue of **NOT ALL** geo field selection being restored when switching among index patterns
Refactor
1. Removed the component state of `geoFields` and `selectedField` as these can be derived from existing data
2. Added a ref object `memorizedForm` to "cache" the index-pattern-related form selection so that user selections can be restored when changing the index pattern back and forth
For more information on following …
=> fix: filters not reset when index pattern changed

public/components/map_container/map_container.tsx, public/components/map_container/mapsFooter.test.tsx, public/components/map_container/mapsFooter.tsx
Move zoom and coordinates as separate component.
We don't have to render zoom/coordiantes if there is no change in maps movement.
Added unit test to check render
=> Move zoom and coordinates as separate component

common/index.ts, public/components/map_container/map_container.tsx, public/components/tooltip/create_tooltip.tsx, public/model/mapLayerType.ts, public/utils/getIntialConfig.ts
Added new property that allows users to disable tooltip on hover. The default value is false to keep
backward compatability. We will revisit the ideal
default value based on user's feedback in later release.
#259 
=> Introduce disable tooltip on hover property

public/model/geo/filter.test.ts, public/model/geo/filter.ts, public/model/layerRenderController.ts
Added Geo Shape Query Filter to build geo shape query for given shape , relations and label.
#213 
=> Add geo shape query filter

package.json, public/components/draw/modes/rectangle.ts, yarn.lock
Mapbox-gl-draw doesn't support rectangle natively, but supports an option to add custom mode.
This PR will create new custom mode using types available for extension. This is typescript version of same
mode that is available in geojson.io.
- Adds rectangle as custom mode
#213 
=> Add rectangle as custom mode

public/components/map_container/map_container.tsx, public/components/toolbar/spatial_filter/draw_tooltip.tsx, public/components/toolbar/spatial_filter/filter_input_panel.tsx
Add tooltip with instruction how to draw filter on map. This will not allow user to draw. It just provides
instructions on how to draw filter based on selection.
#213 
https://user-images.githubusercontent.com/11067894/223634193-472dfb51-fcdf-48aa-baad-f202f538fcaa.mov
=> Add tooltip to draw shape filter

CHANGELOG.md, public/components/layer_config/documents_config/style/label_config.tsx, public/model/documentLayerFunctions.ts, public/model/map/layer_operations.ts
* For backwards compatibility, set textType to BY_FIELD if textByField is set
* Remove unused beforeLayerId for label layer
https://github.com/opensearch-project/dashboards-maps/issues/321
=> BWC for label textType

CHANGELOG.md, common/index.ts, public/components/map_container/map_container.tsx, public/components/toolbar/spatial_filter/draw_filter_shape.tsx, public/components/toolbar/spatial_filter/filter_by_polygon.tsx
if tooltip state is draw , mount mapbox-gl-draw and change mode accordingly.
Added callback once draw is completed. Currently, callback will reset the draw mode. In future PR, will
add Filter Meta based on draw shape.
#213 
https://user-images.githubusercontent.com/11067894/225174933-0cb198ba-bd62-40fb-9c63-5063da957786.mov
=> Add mapbox-gl draw mode

CHANGELOG.md, public/components/tooltip/display_features.tsx
Avoid trigger tooltip from documents label
https://user-images.githubusercontent.com/90288540/225739081-669f1717-fdf6-41da-8955-08c878a73a7a.mov
=> Avoid trigger tooltip from label

CHANGELOG.md, public/components/map_container/map_container.tsx, public/components/map_top_nav/top_nav_menu.tsx, public/model/OSMLayerFunctions.ts, public/model/customLayerFunctions.ts, public/model/documentLayerFunctions.ts, public/model/layerRenderController.ts, public/model/layersFunctions.ts, public/model/map/layer_operations.ts
Because of async layer rendering, when there are multiple layers, the layers order may change in maplibre, adding a ordering function right after all layers render finished to make sure the order is correct at display. 
Since we're adding the order function to make sure all layers order finally, we can remove beforeLayerId parameters when call `addLayer()` to prevent unnecessary performance waste.
https://github.com/opensearch-project/dashboards-maps/issues/352
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-ori …
=> Sync maplibre layer order after layers rendered

CHANGELOG.md, common/index.ts, public/components/toolbar/spatial_filter/__snapshots__/filter_by_rectangle.test.tsx.snap, public/components/toolbar/spatial_filter/__snapshots__/filter_toolbar.test.tsx.snap, public/components/toolbar/spatial_filter/draw_filter_shape.tsx, public/components/toolbar/spatial_filter/draw_tooltip.tsx, public/components/toolbar/spatial_filter/filter_by_rectangle.test.tsx, public/components/toolbar/spatial_filter/filter_by_rectangle.tsx, public/components/toolbar/spatial_filter/filter_toolbar.tsx
Add rectangle draw mode similar to Polygon.
#213 
https://user-images.githubusercontent.com/11067894/225215461-b2555fbc-3edc-46f5-a07b-876b7313d01e.mov
=> Add support to draw rectangle shape to filter documents

CHANGELOG.md, opensearch_dashboards.json, package.json
Bump version to 2.7.0 in 2.x branch
=> [2.x] Bump to 2.7.0 version

CHANGELOG.md, common/util.ts, public/components/draw/modes/rectangle.ts, public/components/map_container/map_container.tsx, public/components/toolbar/spatial_filter/__snapshots__/filter_toolbar.test.tsx.snap, public/components/toolbar/spatial_filter/draw_tooltip.tsx, public/components/toolbar/spatial_filter/filter_toolbar.tsx
We will be using draw button as toggle. In the meantime, users can cancel once started drawing by pressing Escape key.
=> Remove cancel button on draw shape and use Escape to cancel draw

CHANGELOG.md, common/index.ts, public/components/layer_config/documents_config/document_layer_source.tsx, public/components/map_container/map_container.tsx, public/model/layerRenderController.ts, public/model/mapLayerType.ts, public/model/mapState.ts, public/utils/getIntialConfig.ts
- Add geoshape filter to Map state.
- Refresh data layers if filter is updated.
- Add filter based on field type.
=> Add global geo shape filter while rendering data layers 

CHANGELOG.md, public/components/filter_bar/__snapshots__/filter_bar.test.tsx.snap, public/components/filter_bar/__snapshots__/filter_editor.test.tsx.snap, public/components/filter_bar/__snapshots__/filter_view.test.tsx.snap, public/components/filter_bar/filter_actions.test.ts, public/components/filter_bar/filter_actions.ts, public/components/filter_bar/filter_bar.test.tsx, public/components/filter_bar/filter_bar.tsx, public/components/filter_bar/filter_editor.test.tsx, public/components/filter_bar/filter_editor.tsx, public/components/filter_bar/filter_item.tsx, public/components/filter_bar/filter_options.tsx, public/components/filter_bar/filter_view.test.tsx, public/components/filter_bar/filter_view.tsx, public/components/map_container/map_container.tsx, public/components/map_page/map_page.tsx, public/components/toolbar/spatial_filter/draw_filter_shape.tsx, public/components/toolbar/spatial_filter/spatial_filter.scss, public/model/layerRenderController.ts
Add spatial filter after drawing shape from tool bar.
This also provide options like edit, delete, enable, disable on every filter once added.
If draw filter is active, update button color to display which one is active.
=> Add filter bar to display global geospatial filters

CHANGELOG.md, common/map_saved_object_attributes.ts, public/components/layer_config/layer_config_panel.tsx, public/components/layer_control_panel/hide_layer_button.tsx, public/components/layer_control_panel/layer_control_panel.tsx, public/components/map_container/map_container.tsx, public/model/OSMLayerFunctions.ts, public/model/customLayerFunctions.ts, public/model/documentLayerFunctions.ts, public/model/layerRenderController.ts, public/model/layersFunction.test.ts, public/model/layersFunctions.ts, public/model/map/layer_operations.test.ts, public/model/map/layer_operations.ts
* Add beforeLayerId for documents label, so that the label layer will be added below the next map layer any time to avoid adding it in wrong layer order in some corner case.
* Add test for public/model/layersFunction.ts
* Clean extra MaplibreRef interface
* Set selectedLayerConfig to be undefined after render
=> Add before layer id when adding documents label

cypress/integration/add_saved_object.spec.js
Fix the failing cypress test `add_saved_object.spec.js`
Recording of failed test - https://ci.opensearch.org/ci/dbc/integ-test-opensearch-dashboards/2.7.0/6100/linux/x64/tar/test-results/3473/integ-test/functionalTestDashboards/with-security/test-results/cypress-videos/plugins/custom-import-map-dashboards/add_saved_object.spec.js.mp4
=> Fix failing cypress test

.github/CODEOWNERS
The team is going away, replaced by the list of people in MAINTAINERS.md.
=> Fix: CODEOWNERS.

.github/CODEOWNERS, MAINTAINERS.md
Backport https://github.com/opensearch-project/dashboards-maps/pull/414 to 2.x
=> [backport 2.x][manually]Update repo owners and maintainers

CHANGELOG.md, release-notes/opensearch-dashboards-maps.release-notes-2.8.0.0.md
Adding release notes for 2.8
https://github.com/opensearch-project/dashboards-maps/issues/413
=> Adding release notes for 2.8

public/components/map_container/map_container.tsx
Correct indexPatterns api from services.data.indexPatterns to clean browser console error.
=> Clean console indexPatterns api error

CHANGELOG.md, public/components/layer_config/documents_config/document_layer_source.tsx, public/model/layerRenderController.ts
From 2.9, geoshape supports geo bounding box. Hence, remove the constraint that disables geo bounding box for non geopoint fields.
https://github.com/opensearch-project/dashboards-maps/assets/11067894/1217990f-006f-444f-a27f-26aeaa613ba6
=> Allow filtering geo_shape fields around map extent

public/components/toolbar/spatial_filter/__snapshots__/filter-by_shape.test.tsx.snap
Update snap to pass unit test to 2.x branch, since the node version is different between main and 2.x from OSD
=> Update snap to pass unit test

CHANGELOG.md, public/components/tooltip/create_tooltip.scss, public/components/tooltip/create_tooltip.tsx, public/components/tooltip/tooltipTable.tsx
Followed from https://github.com/opensearch-project/dashboards-maps/issues/458#issuecomment-1817272275, this PR:
1. Removes the redundant padding on tooltip
2. Changes the scroll bar to automatically display on tooltip
Before:
After:
=> Fixed maps tooltip display at dark mode

CHANGELOG.md, package.json
Updates cypress and react-test-renderer dependencies to latest versions in order to align with other dashboards plugins
https://github.com/opensearch-project/dashboards-maps/issues/571
=> Update dependencies to align with other plugins

.github/workflows/cypress-workflow.yml, .github/workflows/unit-tests-workflow.yml, CHANGELOG.md, DEVELOPER_GUIDE.md, cypress/e2e/documentsLayer.cy.js, package.json, public/components/layer_config/documents_config/document_layer_source.tsx, yarn.lock
Update layer source name from `Data source` to `Index pattern` followed from https://github.com/opensearch-project/dashboards-maps/issues/584#issuecomment-1953280806
https://github.com/opensearch-project/dashboards-maps/issues/584
=> Update data layer source name

CHANGELOG.md, public/components/layer_config/layer_basic_settings.test.tsx, public/components/layer_config/layer_basic_settings.tsx, public/model/customLayerFunctions.test.ts, public/model/customLayerFunctions.ts
Fix zoom level type error in custom layer.
Closes https://github.com/opensearch-project/dashboards-maps/issues/604
https://github.com/opensearch-project/dashboards-maps/assets/90288540/e2913b7f-17b1-4b53-af50-59ab38b7abcc
=> Fix zoom level type error in custom layer

CHANGELOG.md, opensearch_dashboards.json, public/application.tsx, public/components/app.tsx, public/components/layer_control_panel/layer_control_panel.tsx, public/components/map_container/map_container.tsx, public/components/map_page/map_page.tsx, public/components/map_top_nav/top_nav_menu.tsx, public/components/maps_list/maps_list.tsx, public/plugin.tsx, public/types.ts, yarn.lock
Support multi data source display in Maps app. In maps list page, it will display all available data source. In maps visualization page, it will display all data sources in using.
https://github.com/opensearch-project/dashboards-maps/assets/90288540/62e66996-9581-46fe-90cd-d6569e392b37
Will add test in another PR in https://github.com/opensearch-project/opensearch-dashboards-functional-test which can mock remote data source.
Part of https://github.com/opensearch-project/dashboards-maps/issues/584
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBU …
=> Support multi data source display in Maps app

CHANGELOG.md, release-notes/opensearch-dashboards-maps.release-notes-2.14.0.0.md
=> Add 2.14 release notes

CHANGELOG.md, public/model/layerRenderController.ts
Add data source reference id in data layer search request to avoid potential search error if there is no local cluster.
=> Add data source reference id in data layer search request

CHANGELOG.md, public/model/customLayerFunctions.test.ts, public/model/customLayerFunctions.ts
`UpdateLayerConfig()` is broken as per https://github.com/opensearch-project/dashboards-maps/issues/601. Specifically, line 36 `maplibreInstance.style.sourceCaches[layerConfig.id].update(maplibreInstance.transform)` throws a object reference error. I suspect `maplibreInstance.transform` is gone by the time it's used. Additionally, there are alot of what seem to be workarounds in the function, namely calling seemingly private methods of MaplibreGL and a spelling mistake. While I am by no means familiar with this codebase, it seems that simply deleting and refreshing the layer+source would be a better option. Especially, since updating wms fields would require a full refresh of tiles anyway.
https://github.com/opensearch-project/dashboards-maps/issues/601
By submitting this pull request, I …
=> Refresh custom wms layer+source on update (issue 601)

public/components/__snapshots__/vector_upload_options.test.tsx.snap, public/components/filter_bar/__snapshots__/filter_editor.test.tsx.snap, public/components/filter_bar/filter_editor.tsx, public/components/filter_bar/filter_options.tsx, public/components/layer_config/custom_map_config/custom_map_source.tsx, public/components/layer_config/documents_config/document_layer_source.tsx, public/components/layer_config/documents_config/style/color_picker.tsx, public/components/layer_config/documents_config/style/document_layer_style.tsx, public/components/layer_config/documents_config/style/label_config.test.tsx, public/components/layer_config/documents_config/style/label_config.tsx, public/components/layer_config/layer_basic_settings.test.tsx, public/components/layer_config/layer_basic_settings.tsx, public/components/layer_config/layer_config_panel.tsx, public/components/maps_list/maps_list.tsx, public/components/show_error_modal.tsx, public/components/toolbar/spatial_filter/filter_input_panel.tsx, public/components/tooltip/tooltipHeaderContent.tsx, public/components/tooltip/tooltipTable.tsx, public/components/vector_upload_options.tsx
Replace instances of `EuiButton` that don't have an explicit sizing attribute to `EuiSmallButton*`.
Replace instances of `Eui<form elements>` that don't have density attributes to `EuiCompressed<form elements>`.
=> Use smaller and compressed varients of buttons and form components 

CHANGELOG.md, opensearch_dashboards.json, package.json, public/components/layer_control_panel/layer_control_panel.tsx, public/components/map_container/map_container.tsx, public/components/map_page/map_page.tsx, public/components/map_top_nav/top_nav_menu.tsx, public/components/maps_list/maps_list.tsx, public/plugin.tsx, public/types.ts
Deprecate maps multi data source display when `data_source` is enabled based on Trineo Maps UX mock.
Part of https://github.com/opensearch-project/dashboards-maps/issues/649
=> Deprecate maps multi data source display

CHANGELOG.md, public/components/maps_list/maps_list.tsx
This PR adds the changes to apply new header to maps listing page when turn on `home:useNewHomePage
` in advanced setting.
The code change in maps-dashboards plugin mainly is moving `Create map` button from table to header by using `HeaderControl` provided from OSD [header collective](https://github.com/AMoo-Miki/OpenSearch-Dashboards/tree/header-collective) branch  navigation component.
This PR is target to `feature/new-header` branch, since above OSD code change isn't available in main branch yet. Will add integ test after this PR and OSD feature code is merged to main.
Part of https://github.com/opensearch-project/dashboards-maps/issues/649
For more information on …
=> Use new header to maps listing page

CHANGELOG.md, public/components/map_top_nav/get_top_nav_config.tsx, public/components/map_top_nav/top_nav_menu.tsx
This PR apply the new header UI in Maps visualization page when `home:useNewHomePage` is enabled.
Will add integ tests for new header UI in separate PR.
Part of https://github.com/opensearch-project/dashboards-maps/issues/649
=> Conditionally use the new Application Header variant on the Maps visualization page

CHANGELOG.md, public/components/maps_list/maps_list.tsx
Since https://github.com/opensearch-project/OpenSearch-Dashboards/pull/7691 merged(thanks @AMoo-Miki), this PR allows conditionally use full width for Maps listing page table when new home page UI is enabled.
Part of #649 
=> Conditionally use full width for Maps listing page table

CHANGELOG.md, public/components/__snapshots__/vector_upload_options.test.tsx.snap, public/components/add_layer_panel/add_layer_panel.tsx, public/components/filter_bar/filter_item.tsx, public/components/filter_bar/filter_options.tsx, public/components/layer_config/base_map_layer_config_panel.tsx, public/components/layer_config/custom_map_config/custom_map_config_panel.tsx, public/components/layer_config/documents_config/document_layer_config_panel.tsx, public/components/layer_config/layer_config_panel.tsx, public/components/layer_control_panel/delete_layer_modal.test.tsx, public/components/layer_control_panel/delete_layer_modal.tsx, public/components/layer_control_panel/layer_control_panel.tsx, public/components/map_container/maps_messages.tsx, public/components/maps_list/maps_list.tsx, public/components/show_error_modal.tsx, public/components/toolbar/spatial_filter/display_draw_helper.tsx, public/components/toolbar/spatial_filter/filter_by_shape.tsx, public/components/toolbar/spatial_filter/filter_input_panel.tsx, public/components/vector_upload_options.tsx
This PR makes consistency and density improvements, including:
1. Using small context menus
2. Using small tabs
3. Using small List Groups
4. Using small font size as normal paragraph font size through 
5. Using semantic headers (H1s on main pages, H2s on modals/flyouts) wrapped under 
6. Only using primary buttons for primary calls to action.
7. Using Plus icons for create use cases and PlusInCricle icon for add use cases.
8. Use Refresh Icon in “Update” buttons
|     Before        |       After        |
| ------------- | ------------- |
| <img width="300" alt="Screenshot 2024-08-20 at 4 35 52 PM" src="https://github.com/user-attachments/assets/a4a8e573-0654-45f6-9f7f-6c9e7fde3993"> | <img width="300" alt="Screenshot 2024-08-20 at 4 36 16 PM" …
=> [Look & Feel] Consistency and Density Changes

.github/workflows/remote-ftr-integ-test-workflow.yml
Bump up actions/upload-artifact to v4 to unblock github action CI failure.
=> Bump up actions/upload-artifact to v4

CHANGELOG.md, public/plugin.tsx
Based on https://github.com/opensearch-project/OpenSearch-Dashboards/pull/8332, maps needs to make some adjustment to flatten the menus in analytics(all) use case.
=> [navigation]feat: update category to flatten menus in analytics(all) use case

CHANGELOG.md, public/components/layer_config/layer_config_panel.tsx
Currently, the layers right pane was designed with the older header in mind, and pushed the page content to the left. The new page header isn't build for a static right pane, and because it is no longer fixed height, it is difficult to move the pushed flyout underneath it without things looking weird. Ideally, this flight was moved to become a panel, but to fix this bug in the short term, this just forces the flyout into overlay mode at the window width it starts creating problems.
Under this new breakpoint (1576, used to be 992), the experience looks like 
N/A …
=> fix: prevent overlay from overlapping new application header

CHANGELOG.md, public/index.scss
The current document layer configuration panels had a grey background due to EuiCollapsibleNavGroup's default styling.
Added CSS override to make EuiCollapsibleNavGroup backgrounds transparent within the layer config panel, ensuring consistent styling across all layer type configurations. It can be applied to other layer type panels as well which need EuiCollapsibleNavGroup.
=> Fix layer config panel background color inconsistency

.github/workflows/remote-ftr-integ-test-workflow.yml, .github/workflows/verify-binary-installation.yml, opensearch_dashboards.json, package.json
=> Bump up version to 3.0.0-beta1

CHANGELOG.md, public/model/map/layer_operations.ts
Fixes label overlap issue. Previously with lots of documents, the default text overlap behavior prevented overlapping labels. [This line](https://github.com/opensearch-project/dashboards-maps/blob/494ea33b5ee27fcb9420141c2885751a914a1fb9/public/model/map/layer_operations.ts#L305) was introduced in #703 and allowed label overlapping, resulting in situations like the following. This reverts this overlapping behavior.
See https://maplibre.org/maplibre-style-spec/layers/#text-allow-overlap for documentation
Pre-3.0:
3.0:
post fix:
n/a …
=> Fix text overlap on symbol layer
