README.md
Adds badges to the README showing status of unit test workflow, codecov, etc. 
=> adds badges to README

DEVELOPER_GUIDE.md, README.md, src/plugins/custom_import_map/babel.config.js, src/plugins/custom_import_map/common/index.ts, src/plugins/custom_import_map/common/util.ts, src/plugins/custom_import_map/package.json, src/plugins/custom_import_map/public/components/__snapshots__/show_error_modal.test.tsx.snap, src/plugins/custom_import_map/public/components/show_error_modal.test.tsx, src/plugins/custom_import_map/public/components/show_error_modal.tsx, src/plugins/custom_import_map/public/components/vector_upload_options.test.tsx, src/plugins/custom_import_map/public/components/vector_upload_options.tsx, src/plugins/custom_import_map/public/plugin.tsx, src/plugins/custom_import_map/public/services.ts, src/plugins/custom_import_map/public/types.ts, src/plugins/custom_import_map/server/plugin.ts
- Adds error modal in warning toast shown for partially indexed features while importing geoJSON file.
- Fixes lint issues for repo
=> Adds error modal and lint fixes

src/plugins/custom_import_map/opensearch_dashboards.json, src/plugins/custom_import_map/package.json
Version changes required for `2.2.0` release
- Will create a branch `2.x` after this PR is merged.
- Will add changes for `3.0.0` to main
=> Adds changes for release 2.2

src/plugins/custom_import_map/opensearch_dashboards.json, src/plugins/custom_import_map/package.json
`main` branch should be in sync with opensearch-dashboards. Bumping main to version 3.0
=> Bumps version to 3.0 in main

release-notes/opensearch-dashboards-maps.release-notes-2.2.0.0.md
Add 2.2.0.0 release note
https://github.com/opensearch-project/dashboards-maps/issues/17
=> Add 2.2.0.0 release note

src/plugins/custom_import_map/public/plugin.tsx
wrap component in context to access services
Issue:
n/a
Signed-off-by: Kawika Avilla <kavilla414@gmail.com>
=> [Bug] attach OpenSearch Dashboards context

release-notes/opensearch-dashboards-maps.release-notes-2.2.0.0.md, src/plugins/custom_import_map/.opensearch_dashboards-plugin-helpers.json, src/plugins/custom_import_map/public/plugin.tsx, src/plugins/custom_import_map/tsconfig.json
Add context to component and included the common
folder.
Issue:
n/a
Signed-off-by: Kawika Avilla <kavilla414@gmail.com>
n/a
=> Add OpenSearch Dashboards context to component and common folder changes

src/plugins/maps_dashboards/.eslintrc.js, src/plugins/maps_dashboards/.gitignore, src/plugins/maps_dashboards/.i18nrc.json, src/plugins/maps_dashboards/README.md, src/plugins/maps_dashboards/common/index.ts, src/plugins/maps_dashboards/opensearch_dashboards.json, src/plugins/maps_dashboards/package.json, src/plugins/maps_dashboards/public/application.tsx, src/plugins/maps_dashboards/public/components/app.tsx, src/plugins/maps_dashboards/public/index.scss, src/plugins/maps_dashboards/public/index.ts, src/plugins/maps_dashboards/public/plugin.ts, src/plugins/maps_dashboards/public/types.ts, src/plugins/maps_dashboards/server/index.ts, src/plugins/maps_dashboards/server/plugin.ts, src/plugins/maps_dashboards/server/routes/index.ts, src/plugins/maps_dashboards/server/types.ts, src/plugins/maps_dashboards/translations/ja-JP.json, src/plugins/maps_dashboards/tsconfig.json
- Adds boilerplate code for new plugin "Maps"
- Adds new tab in the Navigation menu on the left
Ran the following command from OSD to generate a new plugin:
` node scripts/generate_plugin --name mapsDashboards -y`
**Note: _All the code here is auto generated, we will get rid of the temporary code in the future PRs._**
=> Initializes new plugin for Maps

src/plugins/maps_dashboards/opensearch_dashboards.json, src/plugins/maps_dashboards/public/components/app.tsx, src/plugins/maps_dashboards/server/routes/index.ts
- Adds skeleton code for maps landing page
- Adds options for edit/delete/view/search with placeholders for the actual function implementation
- Adds sample data for viewing Maps
Adds landing page to Maps plugin.
=> adds skeleton code for maps landing page

src/plugins/custom_import_map/.opensearch_dashboards-plugin-helpers.json, src/plugins/custom_import_map/opensearch_dashboards.json, src/plugins/custom_import_map/package.json, src/plugins/custom_import_map/public/plugin.tsx, src/plugins/custom_import_map/tsconfig.json
- Merges code from 2.2 into 2.x, PR: https://github.com/opensearch-project/dashboards-maps/pull/34
=> adds commit from 2.2 into 2.x

.github/workflows/cypress-workflow.yml, src/plugins/custom_import_map/opensearch_dashboards.json, src/plugins/custom_import_map/package.json
Update the version of OSD from 2.2.0.0 to 2.3.0.0
#39 
Signed-off-by: Navneet Verma <navneev@amazon.com>
=> Update the version of OSD from 2.2.0.0 to 2.3.0.0

release-notes/opensearch-dashboards-maps.release-notes-2.3.0.0.md
Added release notes for 2.3.0
Signed-off-by: Navneet Verma <navneev@amazon.com>
#39
=> Added release notes for 2.3.0

src/plugins/custom_import_map/opensearch_dashboards.json, src/plugins/custom_import_map/package.json
Signed-off-by: Sayali Gaikawad <gaiksaya@amazon.com>
Bump version to 2.3.1
=> Bump version to 2.3.1

.github/workflows/unit-tests-workflow-for-customImportMap.yml, src/plugins/custom_import_map/package.json, src/plugins/custom_import_map/test/jest.config.js
Add macos and window platform in CI workflow
https://github.com/opensearch-project/dashboards-maps/issues/55
=> Add macos and window platform in CI workflow

src/plugins/custom_import_map/opensearch_dashboards.json, src/plugins/custom_import_map/package.json
Bump version to 2.4.0.0
https://github.com/opensearch-project/dashboards-maps/issues/69
=> Bump version to 2.4.0.0

.whitesource
Signed-off-by: Zelin Hao <zelinhao@amazon.com>
WhiteSource didn't raise this onboarding PR automatically, so I'm helping to raise this to onboard whitesource integration. 
Welcome to [Mend for GitHub.com](https://github.com/apps/mend-for-github-com) (formerly WhiteSource). This is an onboarding PR to help you understand and configure settings before Mend starts scanning your repository for security vulnerabilities.
:vertical_traffic_light: Mend for GitHub.com will start scanning your repository only once you merge this Pull Request. To disable Mend for GitHub.com, simply close this Pull Request. 
---
This PR contains a '.whitesource' configuration file which can be customized to your needs. If no changes were applied to this file, Mend for GitHub.com will use the default configuration. …
=> Add whitesource integration config

release-notes/opensearch-dashboards-maps.release-notes-2.4.0.0.md
=> Adds release notes for 2.4.0

.github/workflows/cypress-workflow.yml, release-notes/opensearch-dashboards-maps.release-notes-2.4.0.0.md, src/plugins/custom_import_map/opensearch_dashboards.json
Version bump to 2.4 for dependent packages
=> Version bump to 2.4 for dependent packages

.github/workflows/unit-tests-workflow-for-customImportMap.yml, custom_import_map/public/components/__snapshots__/vector_upload_options.test.tsx.snap
OSD version bump for unit test
https://github.com/opensearch-project/dashboards-maps/issues/72
=> OSD version bump for unit test

maps_dashboards/ DEVELOPER_GUIDE.md
Add developer guide to maps-dashboards plugin.
Closes https://github.com/opensearch-project/dashboards-maps/issues/105
=> Add developer guide 

src/plugins/custom_import_map/opensearch_dashboards.json, src/plugins/custom_import_map/package.json
=> Version bump to 2.4.1

maps_dashboards/public/components/layer_config/base_map_layer_config_panel.tsx, maps_dashboards/public/components/layer_config/document_layer_config_panel.tsx, maps_dashboards/public/components/layer_config/document_layer_source.tsx, maps_dashboards/public/components/layer_config/layer_basic_settings.tsx, maps_dashboards/public/components/layer_config/layer_config_panel.tsx
Added tabs for OpenSearch Base Map.
Added cards for Document layer settings.
Added cards for Layer Settings.
=> Update UI styling

maps_dashboards/public/model/documentLayerFunctions.ts
This PR fixes the issue documents layer visibility couldn't be rendered by maps saved object visibility property.
https://user-images.githubusercontent.com/90288540/206567005-7c28029f-c9bf-48f7-bcb2-084eead4d805.mov
=> Update documents layer render visibility

maps_dashboards/public/components/layer_config/documents_config/document_layer_source.tsx
Fixed null pointer bug for clearing field.
If no value is selected, provide error for
index and field combo box.
=> Add validation marker for document source

maps_dashboards/common/index.ts, maps_dashboards/public/components/add_layer_panel/add_layer_panel.tsx
Followed with UX design to update the layer icon and color
=> Update layer icon and color

maps_dashboards/public/components/layer_control_panel/layer_control_panel.tsx, maps_dashboards/public/components/tooltip/tooltipClick.tsx, maps_dashboards/public/components/tooltip/tooltipHeaderContent.tsx, maps_dashboards/public/components/tooltip/tooltipTable.tsx, maps_dashboards/public/model/documentLayerFunctions.ts
This will display list of features on tooltip from last layer.
https://user-images.githubusercontent.com/11067894/208552632-c5e80323-de8c-4fa8-9a1e-922f83b1ef92.mov
=> Add tooltip on click

maps_dashboards/public/components/map_top_nav/get_top_nav_config.tsx, maps_dashboards/public/components/map_top_nav/top_nav_menu.tsx
1. Add unique validation for creating / updating map title
2. Fix page title not changed after title update
=> Feat add map saved objects validation

maps_dashboards/public/components/layer_config/base_map_layer_config_panel.tsx, maps_dashboards/public/components/layer_config/documents_config/document_layer_config_panel.tsx, maps_dashboards/public/components/layer_config/layer_basic_settings.tsx, maps_dashboards/public/components/layer_config/layer_config_panel.tsx, maps_dashboards/public/components/layer_control_panel/layer_control_panel.tsx
Display error message if user tries to provide
duplicate name.
=> Add duplicate name validation

maps_dashboards/common/index.ts, maps_dashboards/public/components/add_layer_panel/add_layer_panel.scss, maps_dashboards/public/components/add_layer_panel/add_layer_panel.tsx, maps_dashboards/public/utils/getIntialLayerConfig.ts
Add helpful information for layers
Signed-off-by: raintygao [tygao@amazon.com](mailto:tygao@amazon.com)
=>  Feat: Add helpful information for layers

maps_dashboards/public/components/tooltip/tooltipContainer.tsx, maps_dashboards/public/components/tooltip/tooltipHeaderContent.tsx, maps_dashboards/public/components/tooltip/tooltipTable.tsx, maps_dashboards/public/model/documentLayerFunctions.ts
Tooltip hover will show one of the pages/features from the top layer.
=> Add tooltip for hover

maps_dashboards/public/components/layer_config/documents_config/document_layer_source.tsx
Set collapsible nav open based on contents.
=> Update filters section

maps_dashboards/public/plugin.ts
Signed-off-by: raintygao <tygao@amazon.com>
add validation and redirect for index pattern
=> feat: add validation and redirect for index pattern

maps_dashboards/public/components/layer_control_panel/layer_control_panel.tsx
Add delete layer warning modal when click delete icon from layer control panel.
=> Delete layer modal

maps_dashboards/public/components/layer_config/layer_config_panel.tsx
Fix discard config panel remove layer issue.
1. Add new layer
2. Complete configuration and click update
3. Reopen this layer config panel
4. Click discard
5. This layer will be removed from layers
=> Fix discard config panel remove layer

maps_dashboards/public/components/map_top_nav/top_nav_menu.tsx
Enable map auto refresh with configured interval
=> Enable map auto refresh with configured interval

maps_dashboards/public/components/tooltip/tooltipTable.tsx
=> fix: fixed map tooltip footer misalignment

maps_dashboards/public/model/documentLayerFunctions.ts
Add unique id for each geoshape layer to maplibre after [this](https://github.com/opensearch-project/dashboards-maps/commit/8fac2d9f42816cbab48b26b09f4a04597bfd27f7#diff-9e24001b2ef9253f3369c9053b8165c067b832582f3ae41a55327df32ba60974L86) commit change.
=> Add different id for each geoshape layer

maps_dashboards/public/components/tooltip/tooltipContainer.tsx, maps_dashboards/public/components/tooltip/tooltipTable.tsx
Include layer name as one of the properties for
every feature to identify from where the feature
is be coming from.
=> Include layer name as property

maps_dashboards/public/components/map_container/map_container.tsx, maps_dashboards/public/components/tooltip/tooltipContainer.tsx, maps_dashboards/public/model/documentLayerFunctions.ts
Move tooltip on mousemove to container.
=> Move tooltip outside document layer

maps_dashboards/public/components/tooltip/tooltipTable.tsx
reset feature array for every table.
=> Reset feature array

maps_dashboards/package-lock.json, maps_dashboards/package.json, maps_dashboards/public/model/documentLayerFunctions.ts, maps_dashboards/public/utils/geo_formater.ts, maps_dashboards/yarn.lock
Added dependency to wellknown package to
parse WKT format into GeoJSON.
=> Add support for WKT format

common/index.ts, public/components/add_layer_panel/add_layer_panel.tsx, public/components/layer_config/custom_map_config/custom_map_source.tsx, public/components/layer_config/documents_config/document_layer_source.tsx, public/components/layer_control_panel/layer_control_panel.tsx
1. Rename reference layer to base layer
2. Update description text
=> Update text after review

opensearch_dashboards.json, package.json
Update app id name to customImportMapDashboards from customImportMap, which is required from infra team.
=> Update app id name to customImportMapDashboards

public/components/layer_config/custom_map_config/custom_map_source.tsx, public/components/layer_config/documents_config/document_layer_source.tsx, public/components/layer_config/documents_config/document_layer_style.tsx, public/components/layer_config/layer_basic_settings.tsx, yarn.lock
Add fullWidth property to some components to make sure layout same as normal size at large size screen(e.g. 32 inch screen) . 
Before:
After:
=> Add fullWidth for large size screen display

public/components/layer_config/custom_map_config/custom_map_source.tsx
=> Update helper text

release-notes/opensearch-dashboards-maps.release-notes-2.5.0.0.md
Adds release notes for 2.5
#160 
=> Add  release notes for 2.5

public/model/geo/filter.test.ts, public/model/geo/filter.ts, public/model/layerRenderController.ts, public/model/map/__mocks__/map.ts, public/model/map/bondary.test.ts, public/model/map/boundary.ts, public/model/map/layer_operations.test.ts, test/setup.jest.js
move map bounds to model and added unit test.
=> Refactor geo bounding box filter

.github/workflows/cypress-workflow.yml, .github/workflows/unit-tests-workflow.yml, cypress/integration/documentsLayer.spec.js, opensearch_dashboards.json, package.json
Update 2.x branch version to 2.6
https://github.com/opensearch-project/dashboards-maps/issues/230
=> Update 2.x branch version to 2.6

cypress/integration/documentsLayer.spec.js, cypress/integration/opensearchMapLayer.spec.js
Signed-off-by: Naveen Tatikonda <navtat@amazon.com>
Delete Sample data after running a cypress test.
=> Delete Sample data after running cypress test

public/model/documentLayerFunctions.ts, public/model/map/__mocks__/layer.ts, public/model/map/__mocks__/map.ts, public/model/map/layer_operations.test.ts, public/model/map/layer_operations.ts
Backport https://github.com/opensearch-project/dashboards-maps/commit/538628c448503b819cfbbb5a1462dce97efd9d54 from https://github.com/opensearch-project/dashboards-maps/pull/222
=> [Backport 2.x] Refactor add layer operations

DEVELOPER_GUIDE.md, MAINTAINERS.md
* Update development document for how to run, test and build plugin.
* Update current maintainers.
https://github.com/opensearch-project/dashboards-maps/issues/229
=> Update development and maintainer document

public/components/layer_control_panel/hide_layer_button.test.tsx, public/components/layer_control_panel/hide_layer_button.tsx, public/components/layer_control_panel/layer_control_panel.tsx, public/model/documentLayerFunctions.ts, public/model/map/layer_operations.test.ts, public/model/map/layer_operations.ts
Refactor hide layer button from layerControlPanel into individual component and added test.
=> Refactor hide layer button

.github/workflows/cypress-workflow.yml, .github/workflows/unit-tests-workflow.yml
Backport https://github.com/opensearch-project/dashboards-maps/commit/c3ebf3ab470403e79356ca3a5d741f66d6983d3e from #277
=> [Backport 2.x][Manual]Fix Node.js and Yarn installation in CI (#277)

release-notes/opensearch-dashboards-maps.release-notes-2.6.0.0.md
=> Add 2.6.0 release notes

.gitignore, public/components/layer_control_panel/layer_control_panel.scss
Backport https://github.com/opensearch-project/dashboards-maps/pull/294 to 2.x
=> [Backport 2.x]Show scroll bar when panel height reaches container bottom

common/index.ts, public/components/map_container/map_container.tsx, public/components/tooltip/display_features.tsx
Added property to decide whether tooltip to display features or not. 
This will be required if tooltip is used to draw shape.
=> Refactor tooltip setup as component

public/components/layer_config/documents_config/document_layer_source.tsx
This is due to the inappropriate in-memory cache key been used to cache user selection of filters and geo filter selection.
It was using the index pattern id as the cache key, but different layer may have the same index pattern selected.
To fix the issue, we changed to use layerConfig id + index pattern id as the cache key
Fixed #323
=> fix: layer filter setting been reset unexpectedly

common/index.ts
Since layer panel has scroll bar, we can allow user to add up to 100. Later, this will be moved to map settings.
=> Update max supported layer count

CHANGELOG.md, public/components/map_container/map_container.tsx, public/model/layerRenderController.ts, public/model/layersFunctions.ts, public/model/mapLayerType.ts
* Fix data render in dashboard mode when enable around map filter
* Refactor layer render functions
Closes https://github.com/opensearch-project/dashboards-maps/issues/341
=> Fix data query in dashboard mode when enable around map filter

CHANGELOG.md, public/components/draw/modes/rectangle.ts, public/components/toolbar/spatial_filter/draw_tooltip.tsx
Update esc key press check on key up.
Update popup information.
=> Update listener on KeyUp

CHANGELOG.md, public/components/map_container/map_container.tsx, public/components/map_page/map_page.tsx, public/components/map_top_nav/top_nav_menu.tsx, public/embeddable/map_component.tsx, public/model/layerRenderController.ts
* Add search query ability on map top nav bar
* Remove unused timeRange(from view mode) on top nav component
* Refactor layerRenderController
https://user-images.githubusercontent.com/90288540/228728085-467c9298-61aa-4e01-b37d-49853a0c445e.mov
https://github.com/opensearch-project/dashboards-maps/issues/369
=> Add search query ability on map

CHANGELOG.md, public/components/map_container/map_container.tsx, public/components/map_container/maps_messages.tsx, public/model/OSMLayerFunctions.ts, public/model/layerRenderController.ts
Display warning message as toast notification if OpenSearch base map is used in conflicting regions.
https://user-images.githubusercontent.com/89161683/230252637-dca25d89-ff5f-4a61-82f3-4846fe604672.mov
https://github.com/opensearch-project/dashboards-maps/issues/251
=> Toast Warning Message if OpenSearch base map is used in conflicting regions

CHANGELOG.md, release-notes/opensearch-dashboards-maps.release-notes-2.7.0.0.md
Add 2.7.0 Release Notes
https://github.com/opensearch-project/dashboards-maps/issues/373
=> Add 2.7.0 Release Notes

release-notes/opensearch-dashboards-maps.release-notes-2.9.0.0.md
Add 2.9.0 release note
https://github.com/opensearch-project/dashboards-maps/issues/427
=> Add 2.9.0 release note

package.json, release-notes/opensearch-dashboards-maps.release-notes-2.9.0.0.md, yarn.lock
=> bump tough cookie

common/config.ts
Update vector tile styles manifest endpoint
=> Update vector tile styles manifest endpoint

CHANGELOG.md, release-notes/opensearch-dashboards-maps.release-notes-2.10.0.0.md
Created release notes for 2.10 release
#443 
=> Created release notes for 2.10 release

opensearch_dashboards.json, package.json, public/components/toolbar/spatial_filter/__snapshots__/filter-by_shape.test.tsx.snap
Bump plugin version to 2.11 and update unit test snap
=> Bump plugin version to 2.11 and update unit test snap

.gitignore, CHANGELOG.md, release-notes/opensearch-dashboards-maps.release-notes-2.11.0.0.md
Add 2.11 release note
https://github.com/opensearch-project/dashboards-maps/issues/475
=> Add 2.11 release note

.github/workflows/unit-tests-workflow.yml
Onboard jenkins prod docker images to github actions
#519
=> Onboard jenkins prod docker images to github actions

CHANGELOG.md, release-notes/opensearch-dashboards-maps.release-notes-2.13.0.0.md
Add release notes for 2.13.0 release
=> Add release notes for 2.13.0 release

CHANGELOG.md, opensearch_dashboards.json, public/application.tsx, public/components/app.tsx, public/components/layer_control_panel/layer_control_panel.tsx, public/components/map_container/map_container.tsx, public/components/map_page/map_page.tsx, public/components/map_top_nav/top_nav_menu.tsx, public/components/maps_list/maps_list.tsx, public/plugin.tsx, public/types.ts, yarn.lock
=> [backport 2.x] Support multi data source display in Maps app (#611)

CHANGELOG.md, release-notes/opensearch-dashboards-maps.release-notes-2.15.0.0.md
=> Add release notes for 2.15.0

CHANGELOG.md, public/plugin.tsx
Add support new navigation for maps
Maps for https://github.com/opensearch-project/OpenSearch-Dashboards/issues/7029
=> Add support new navigation for maps

public/plugin.tsx
Update new navigation groups from latest UX change.
N/A
=> Update new navigation groups

CHANGELOG.md, release-notes/opensearch-dashboards-maps.release-notes-2.16.0.0.md
=> Adds release notes for 2.16

public/plugin.tsx
=> [navigation]feat: do not show in all use case

CHANGELOG.md, opensearch_dashboards.json, public/components/layer_control_panel/layer_control_panel.tsx, public/components/map_container/map_container.tsx, public/components/map_page/map_page.tsx, public/components/map_top_nav/top_nav_menu.tsx, public/components/maps_list/maps_list.tsx, public/plugin.tsx, public/types.ts
Backport #651 into 2.x branch.
=> [backport 2.x] Deprecate maps multi data source display (#651)

CHANGELOG.md, public/components/map_top_nav/get_top_nav_config.tsx, public/components/map_top_nav/top_nav_menu.tsx, public/components/maps_list/maps_list.tsx
Merge code from [feature/new-header](https://github.com/opensearch-project/dashboards-maps/tree/feature/new-header) branch to main branch.
It contains code changes from PRs:
#653 
#654 
#655 
#649
=> [feature to main] Use new header in Maps when new home UI is enabled

CHANGELOG.md, release-notes/opensearch-dashboards-maps.release-notes-2.17.0.0.md
=> Add release notes for 2.17

CHANGELOG.md, public/components/layer_config/documents_config/style/document_layer_style.tsx, public/components/layer_config/documents_config/style/label_config.tsx, public/components/layer_control_panel/layer_control_panel.tsx, public/components/map_top_nav/get_top_nav_config.tsx
=> Fix dynamic uses of i18n

opensearch_dashboards.json
Add "dataSource", "dataSourceManagement" to maps-dashboards plugin as dependencies for region maps multi data source. 
=> Add multi data source dependencies plugins

opensearch_dashboards.json
=> [backport 2.x] Add multi data source dependencies plugins

CHANGELOG.md, release-notes/opensearch-dashboards-maps.release-notes-2.19.0.0.md
Add Release Notes for 2.19.0.0
Issue: https://github.com/opensearch-project/dashboards-maps/issues/687
=> Add Release Notes for 2.19.0.0

.github/workflows/remote-ftr-integ-test-workflow.yml, .github/workflows/verify-binary-installation.yml, CHANGELOG.md, opensearch_dashboards.json, package.json
Bump dashboards-maps to version 3.0.0.0-alpha1
#442 
=> Bump dashboards-maps to version 3.0.0.0-alpha1

CHANGELOG.md, release-notes/opensearch-dashboards-maps.release-notes-3.0.0.0-alpha1.md
Creating release notes for 3.0-alpha1 release.
[442](https://github.com/opensearch-project/dashboards-maps/issues/442)
=> add release notes for 3.0 alpha

package.json
=> Bump up depdency version

yarn.lock
Bump up yarn.lock file dependency version
=> Bump up yarn.lock file dependency version

release-notes/opensearch-dashboards-maps.release-notes-3.0.0.0-beta1.md
add release notes for 3.0 beta1 release
#442 
=> add release notes for 3.0 beta1

CHANGELOG.md, release-notes/opensearch-dashboards-maps.release-notes-3.0.0.0.md
add release notes for 3.0 release
=> [backport 3.0] add release notes for 3.0
